name = "remix-cloudflare-workers"
type = "javascript"

zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-05-12"

kv_namespaces = [
  { binding = "FUMIHOGO_KV", id = "7355abfdfbdd4597bbcfab0af3a40f3f" }
]

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"

[build.upload]
format="service-worker"


